### ISSUE TITLE
关于使用的问题

### ISSUE THREAD

**Issue by 1359450511** [RT-Thread-packages/infrared_framework#7]
请问这个软件包怎么使用，有没有使用的demo，文档中readme中的这个user_read_api("nec",&infrared_data)这个函数到底该怎么去写呢

**Comment by armink** [comment]
可以看下 IoT Board 里的 红外示例

**Comment by 1359450511** [comment]
好的谢谢 ------------------ 原始邮件 ------------------
发件人: "朱天龙 (Armink)"<notifications@github.com>
发送时间: 2020年5月18日(星期一) 下午3:56
收件人: "RT-Thread-packages/infrared_framework"<infrared_framework@noreply.github.com>;
抄送: "1359450511"<1359450511@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [RT-Thread-packages/infrared_framework] 关于使用的问题 (#7)




 
可以看下 IoT Board 里的 红外示例
 
&mdash;
